name: Init S3 Terraform backend

on:
  workflow_dispatch:
    inputs:
      region:
        required: true
        description: AWS Region
      bucket_name:
        required: true
        description: AWS S3 Bucket Name
      table_name:
        description: AWS DynamoDB Table Name
      aws_access_key_id:
        description: AWS access key id
      aws_secret_access_key:
        description: AWS secret access key

jobs:
  init_s3_terraform_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Make script executable
        run: chmod +x ./init.sh
      - name: Create AWS resources
        run: |
            ./init.sh \
              -r "${{ github.event.inputs.region }}" \
              -b "${{ github.event.inputs.bucket_name }}" \
              -t "${{ github.event.inputs.table_name }}" \
              -a "${{ github.event.inputs.aws_access_key_id }}" \
              -s "${{ github.event.inputs.aws_secret_access_key }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  remove_s3_terraform_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Make script executable
        run: chmod +x ./remove.sh
      - name: Remove AWS resources
        run: |
          ./remove.sh \
            -r "${{ github.event.inputs.region }}" \
            -b "${{ github.event.inputs.bucket_name }}" \
            -t "${{ github.event.inputs.table_name }}" \
            -a "${{ github.event.inputs.aws_access_key_id }}" \
            -s "${{ github.event.inputs.aws_secret_access_key }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
